#!usr/bin/python3
import crypt
import getpass

#
# This script will take information of user, device id and password.
# username and device need to be in the same exact form as dictated in your Salt configuration.
# As output it will provide a salt command that can be used to set the password.
# 

print("Create a password hash!")
print()
print("username and device ID need to be in the same exact form as in your Salt configuration.")
print()
username = input("Enter username:")
device = input("Enter device:")
print()
print()
password = getpass.getpass("New password:")
password2 = getpass.getpass("Type password again:")
print()
if password == password2:
	hash = crypt.crypt(password, crypt.mksalt(crypt.METHOD_SHA512))
	print('User: ' + username)
	print('Device: ' + device)
	print('Password hash:' + hash)
	print()
	print('Run the following command to make changes:')
	print()
	print("sudo salt '" + device + "' shadow.set_password " +  username + " " + "'" +  hash + "'")
else:
	print("Passwords don't match")

